apiVersion: batch/v1
kind: Job
metadata:
  initializers:
    pending: []
  annotations:
    artifact.spinnaker.io/location: panorama
    artifact.spinnaker.io/name: 9970-publish-3fe3d3d6e247abe4-test
    artifact.spinnaker.io/type: kubernetes/job
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"artifact.spinnaker.io/location":"panorama","artifact.spinnaker.io/name":"9970-publish-3fe3d3d6e247abe4-test","artifact.spinnaker.io/type":"kubernetes/job","moniker.spinnaker.io/application":"dataflowteam3502970","moniker.spinnaker.io/cluster":"job 9970-publish-3fe3d3d6e247abe4-test"},"labels":{"app.kubernetes.io/managed-by":"spinnaker","app.kubernetes.io/name":"dataflowteam3502970","k8s-app":"9970-publish","qcloud-app":"9970-publish","xverse-render-module":"publish","xverse-task-id":"9970"},"name":"9970-publish-3fe3d3d6e247abe4-test","namespace":"panorama"},"spec":{"backoffLimit":1,"completions":1,"parallelism":1,"selector":{},"template":{"metadata":{"annotations":{"artifact.spinnaker.io/location":"panorama","artifact.spinnaker.io/name":"9970-publish-3fe3d3d6e247abe4-test","artifact.spinnaker.io/type":"kubernetes/job","eks.tke.cloud.tencent.com/cpu-type":"amd,intel","eks.tke.cloud.tencent.com/root-cbs-size":"160","eks.tke.cloud.tencent.com/security-group-id":"sg-lv87o8r3","moniker.spinnaker.io/application":"dataflowteam3502970","moniker.spinnaker.io/cluster":"job 9970-publish-3fe3d3d6e247abe4-test"},"labels":{"app.kubernetes.io/managed-by":"spinnaker","app.kubernetes.io/name":"dataflowteam3502970"}},"spec":{"containers":[{"args":["start.sh"],"command":["bash"],"env":[{"name":"PATH","value":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},{"name":"TASK_ID","value":"9970"},{"name":"APPID","value":"11025"},{"name":"SKIN_ID","value":"15202"},{"name":"SKIN_VERSION","value":"B00024"},{"name":"PATH_NAMES_JSON","value":"[{\"path\":\"/cfs/waferlu/tasks/dataflow_tasks/9969_15202B00024\",\"name\":\"4af2d2e864f60d69\"}]"},{"name":"BLOCK_ID","value":""},{"name":"ENV","value":"prd"}],"image":"ccr.ccs.tencentyun.com/panorama/publish:v0.0.2","imagePullPolicy":"IfNotPresent","name":"publish-docker","resources":{"limits":{"cpu":"32","memory":"64Gi"},"requests":{"cpu":"32","memory":"64Gi"}},"securityContext":{"privileged":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cfs0","name":"turbocfs0"},{"mountPath":"/cfs","name":"turbocfs"}],"workingDir":"/mnt/datadisk0"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"qcloudregistrykey"}],"restartPolicy":"OnFailure","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":300,"volumes":[{"name":"turbocfs0","persistentVolumeClaim":{"claimName":"pvc-cfsturbo"}},{"name":"turbocfs","persistentVolumeClaim":{"claimName":"pvc-cfsturbo2"}}]}}}}
    moniker.spinnaker.io/application: dataflowteam3502970
    moniker.spinnaker.io/cluster: job 9970-publish-3fe3d3d6e247abe4-test
  creationTimestamp: "2022-12-13T13:16:52Z"
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: dataflowteam3502970
    k8s-app: 9970-publish
    qcloud-app: 9970-publish
    xverse-render-module: publish
    xverse-task-id: "9970"
  name: 9970-publish-3fe3d3d6e247abe4-test
  namespace: panorama
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  selector: {}
  template:
    metadata:
      annotations:
        artifact.spinnaker.io/location: panorama
        artifact.spinnaker.io/name: 9970-publish-3fe3d3d6e247abe4-test
        artifact.spinnaker.io/type: kubernetes/job
        eks.tke.cloud.tencent.com/cpu-type: amd,intel
        eks.tke.cloud.tencent.com/root-cbs-size: "160"
        eks.tke.cloud.tencent.com/security-group-id: sg-lv87o8r3
        moniker.spinnaker.io/application: dataflowteam3502970
        moniker.spinnaker.io/cluster: job 9970-publish-3fe3d3d6e247abe4-test
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: spinnaker
        app.kubernetes.io/name: dataflowteam3502970
        job-name: 9970-publish-3fe3d3d6e247abe4-test
    spec:
      containers:
      - args:
        - infinity
        command:
        - sleep
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TASK_ID
          value: "9970"
        - name: APPID
          value: "11025"
        - name: SKIN_ID
          value: "15202"
        - name: SKIN_VERSION
          value: B00024
        - name: PATH_NAMES_JSON
          value: '[{"path":"/cfs/waferlu/tasks/dataflow_tasks/9969_15202B00024","name":"4af2d2e864f60d69"}]'
        - name: BLOCK_ID
        - name: ENV
          value: prd
        image: ccr.ccs.tencentyun.com/panorama/publish:v0.0.2
        imagePullPolicy: IfNotPresent
        name: publish-docker
        resources:
          limits:
            cpu: "32"
            memory: 64Gi
          requests:
            cpu: "32"
            memory: 64Gi
        securityContext:
          privileged: false
          procMount: null
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cfs0
          name: turbocfs0
        - mountPath: /cfs
          name: turbocfs
        workingDir: /mnt/datadisk0
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 300
      volumes:
      - name: turbocfs0
        persistentVolumeClaim:
          claimName: pvc-cfsturbo
      - name: turbocfs
        persistentVolumeClaim:
          claimName: pvc-cfsturbo2
status:
  conditions:
  - lastProbeTime: "2022-12-13T13:17:51Z"
    lastTransitionTime: "2022-12-13T13:17:51Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 1
  startTime: "2022-12-13T13:16:52Z"